# Generated by Django 6.0 on 2026-01-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='category',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='created_at',
        ),
    ]
